name: "bluebell"
mode: "dev"
port: 8081
version: "v0.1.2"
start_time: "20210124"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "121.4.129.249"
  port: 3306
  user: "root"
  password: "550507808"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "121.4.129.249"
  port: 6379
  password: "hello"
  db: 0
  pool_size: 100